"""
One way to open the app's database, on SQLite or PostgreSQL.

    DATABASE_URL unset                         -> SQLite file (db_core.DB_PATH), as before
    DATABASE_URL=postgresql://user:pw@host/db  -> PostgreSQL

The rest of the backend was written against Python's sqlite3 module and keeps
its SQL. For PostgreSQL this module hands out a connection that behaves the
same way, so the calling code does not change:

  - "?" placeholders are accepted (translated to psycopg's "%s").
  - Rows can be read by position or by column name, and dict(row) works.
  - Errors are raised as the sqlite3 exception classes the code already
    catches (sqlite3.IntegrityError, sqlite3.OperationalError, sqlite3.Error).
  - A failed statement does not poison the transaction: each statement runs
    inside a savepoint, which matches SQLite's behaviour.
  - cursor.lastrowid works after an INSERT into a table with a generated id.
  - CREATE TABLE statements written for SQLite are translated (see translate_ddl).
  - True/False parameters become 1/0, because flags are stored in INTEGER columns.
  - NUMERIC results (AVG, ROUND) come back as float, not Decimal.

Only code that is genuinely different between the two databases needs to ask
which one it is on (IS_POSTGRES); helpers for the common cases are below.
"""

from __future__ import annotations

import os
import re
import sqlite3
from decimal import Decimal

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
IS_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))


# ── SQL translation ──────────────────────────────────────────────────────────

def translate_params(sql: str) -> str:
    """'?' -> '%s' outside quoted strings; literal '%' is doubled so psycopg doesn't read it as a placeholder."""
    out, in_string = [], False
    for ch in sql:
        if ch == "'":
            in_string = not in_string
            out.append(ch)
        elif ch == "%":
            out.append("%%")
        elif ch == "?" and not in_string:
            out.append("%s")
        else:
            out.append(ch)
    return "".join(out)


_UTC_TEXT_NOW = "to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')"
_DDL_RULES = [
    # SQLite gives an INTEGER PRIMARY KEY an automatic value; PostgreSQL needs to be told.
    (re.compile(r"\bINTEGER\s+PRIMARY\s+KEY(\s+AUTOINCREMENT)?\b", re.I), "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    # PostgreSQL's REAL is 4 bytes (about 7 digits): not enough for money. SQLite's REAL is 8 bytes.
    (re.compile(r"\bREAL\b", re.I), "DOUBLE PRECISION"),
    # Timestamps are stored as text in SQLite's 'YYYY-MM-DD HH:MM:SS' format; keep the same format.
    (re.compile(r"\bDEFAULT\s+CURRENT_TIMESTAMP\b", re.I), f"DEFAULT ({_UTC_TEXT_NOW})"),
]


def translate_ddl(sql: str) -> str:
    """Make a CREATE TABLE written for SQLite valid on PostgreSQL."""
    for pattern, replacement in _DDL_RULES:
        sql = pattern.sub(replacement, sql)
    return sql


def _split_statements(script: str) -> list[str]:
    statements, current, in_string = [], [], False
    for ch in script:
        if ch == "'":
            in_string = not in_string
        if ch == ";" and not in_string:
            statements.append("".join(current))
            current = []
        else:
            current.append(ch)
    statements.append("".join(current))
    cleaned = []
    for s in statements:
        body = "\n".join(line for line in s.splitlines() if not line.strip().startswith("--")).strip()
        if body:
            cleaned.append(body)
    return cleaned


# ── PostgreSQL connection that looks like sqlite3's ──────────────────────────

class Row(tuple):
    """A result row readable by index or column name, like sqlite3.Row."""

    __slots__ = ()
    _columns: tuple = ()

    def __getitem__(self, key):
        if isinstance(key, str):
            try:
                return tuple.__getitem__(self, self._index[key])
            except KeyError:
                raise IndexError(f"No item with that key: {key}") from None
        return tuple.__getitem__(self, key)

    def keys(self):
        return list(self._columns)


def _row_class(columns: tuple):
    return type("Row", (Row,), {"__slots__": (), "_columns": columns, "_index": {c: i for i, c in enumerate(columns)}})


def _plain(value):
    return float(value) if isinstance(value, Decimal) else value


def _convert_error(exc):
    import psycopg

    message = str(exc).strip()
    if isinstance(exc, psycopg.errors.IntegrityError):
        # sqlite3 says "UNIQUE constraint failed"; some callers look for the word UNIQUE.
        if isinstance(exc, psycopg.errors.UniqueViolation):
            message = f"UNIQUE constraint failed: {message}"
        return sqlite3.IntegrityError(message)
    if isinstance(exc, (psycopg.errors.UndefinedTable, psycopg.errors.UndefinedColumn, psycopg.errors.SyntaxError,
                        psycopg.OperationalError)):
        return sqlite3.OperationalError(message)
    return sqlite3.DatabaseError(message)


class PgCursor:
    def __init__(self, connection: "PgConnection"):
        self._connection = connection
        self._cursor = connection._raw.cursor()
        self._row_class = None
        self._was_insert = False

    # sqlite3 callers assign these; rows are always name-addressable here.
    row_factory = None

    def execute(self, sql, params=()):
        import psycopg

        self._was_insert = sql.lstrip()[:6].upper() == "INSERT"
        statement = sql
        if re.match(r"\s*CREATE\s+TABLE", sql, re.I):
            statement = translate_ddl(sql)
        if params:
            statement = translate_params(statement)
            params = tuple(int(p) if isinstance(p, bool) else p for p in params)
        # A savepoint per statement: if it fails, only this statement is undone and the connection
        # stays usable, as with SQLite. Issued as plain SQL on purpose: psycopg's own
        # connection.transaction() would COMMIT when used outside a transaction, and nothing here
        # may be committed before the caller calls commit().
        try:
            self._cursor.execute("SAVEPOINT smartfin_statement")
            try:
                self._cursor.execute(statement, params or None)
            except psycopg.Error:
                self._connection._raw.execute("ROLLBACK TO SAVEPOINT smartfin_statement")
                raise
            # RELEASE through a second cursor so this one keeps its result set
            self._connection._raw.execute("RELEASE SAVEPOINT smartfin_statement")
        except psycopg.Error as e:
            raise _convert_error(e) from e
        self._row_class = None
        return self

    def executemany(self, sql, seq_of_params):
        for params in seq_of_params:
            self.execute(sql, params)
        return self

    def _wrap(self, row):
        if row is None:
            return None
        if self._row_class is None:
            self._row_class = _row_class(tuple(d.name for d in self._cursor.description))
        return self._row_class(_plain(v) for v in row)

    def fetchone(self):
        return self._wrap(self._cursor.fetchone()) if self._cursor.description else None

    def fetchall(self):
        return [self._wrap(r) for r in self._cursor.fetchall()] if self._cursor.description else []

    def fetchmany(self, size=None):
        rows = self._cursor.fetchmany(size) if size else self._cursor.fetchmany()
        return [self._wrap(r) for r in rows]

    def __iter__(self):
        return iter(self.fetchall())

    @property
    def rowcount(self):
        return self._cursor.rowcount

    @property
    def description(self):
        return [(d.name, None, None, None, None, None, None) for d in (self._cursor.description or [])] or None

    @property
    def lastrowid(self):
        """The id generated by the last INSERT on this connection, or None."""
        if not self._was_insert:
            return None
        import psycopg

        raw = self._connection._raw
        try:
            raw.execute("SAVEPOINT smartfin_lastval")
            try:
                value = raw.execute("SELECT lastval()").fetchone()[0]
            except psycopg.Error:      # no generated id in this session
                raw.execute("ROLLBACK TO SAVEPOINT smartfin_lastval")
                return None
            raw.execute("RELEASE SAVEPOINT smartfin_lastval")
            return value
        except psycopg.Error:
            return None

    def close(self):
        self._cursor.close()


class PgConnection:
    def __init__(self, url: str):
        import psycopg

        try:
            self._raw = psycopg.connect(url, connect_timeout=10)
        except psycopg.Error as e:
            raise sqlite3.OperationalError(f"could not connect to PostgreSQL: {str(e).strip()}") from e

    row_factory = None  # accepted and ignored: see PgCursor

    def cursor(self):
        return PgCursor(self)

    def execute(self, sql, params=()):
        return PgCursor(self).execute(sql, params)

    def executemany(self, sql, seq_of_params):
        return PgCursor(self).executemany(sql, seq_of_params)

    def executescript(self, script):
        cursor = PgCursor(self)
        for statement in _split_statements(script):
            cursor.execute(statement)
        self.commit()
        return cursor

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        if exc_type is None:
            self.commit()
        else:
            self.rollback()
        return False


# ── Public API ───────────────────────────────────────────────────────────────

def is_app_database(path) -> bool:
    """True when `path` means "the app's database" rather than some other SQLite file (tests use their own)."""
    if path is None:
        return True
    from db_core import DB_PATH
    return os.path.abspath(str(path)) == os.path.abspath(DB_PATH)


def connect(path=None):
    """
    Open the database. `path` is the SQLite file the caller would have opened; when the app is
    configured for PostgreSQL and `path` is the app's own database, a PostgreSQL connection is returned.
    """
    if IS_POSTGRES and is_app_database(path):
        return PgConnection(DATABASE_URL)
    if path is None:
        from db_core import DB_PATH
        path = DB_PATH
    # Plain connection, exactly what callers got before; those that want sqlite3.Row set it themselves.
    return sqlite3.connect(path)


def is_postgres(conn) -> bool:
    return isinstance(conn, PgConnection)


def table_exists(conn, table: str) -> bool:
    if is_postgres(conn):
        row = conn.execute("SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = ?",
                           (table,)).fetchone()
    else:
        row = conn.execute("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?", (table,)).fetchone()
    return row is not None


def table_names(conn) -> list[str]:
    if is_postgres(conn):
        rows = conn.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = current_schema()").fetchall()
    else:
        rows = conn.execute("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'").fetchall()
    return sorted(r[0] for r in rows)


def column_names(conn, table: str) -> list[str]:
    """Columns of a table, in order. `table` must be a known table name, never user input."""
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", table):
        raise ValueError(f"not a table name: {table!r}")
    if is_postgres(conn):
        rows = conn.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ? "
            "ORDER BY ordinal_position", (table,)).fetchall()
        return [r[0] for r in rows]
    return [r[1] for r in conn.execute(f'PRAGMA table_info("{table}")')]


def add_column_if_missing(conn, table: str, column: str, definition: str) -> bool:
    """ALTER TABLE ... ADD COLUMN, skipped when the column is already there. Returns True if it was added."""
    if column in column_names(conn, table):
        return False
    conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")
    return True
