"""
Where uploaded profile pictures are kept.

    SMARTFIN_UPLOADS_BUCKET unset  -> a folder on disk (db_core.UPLOAD_DIR), as before
    SMARTFIN_UPLOADS_BUCKET=name   -> that S3 bucket, under profile_pictures/

A folder only works while there is a single backend: with two copies running, a
picture saved by one is missing on the other. S3 is shared by all of them.

The bucket stays private. Pictures are still served by the backend at
/uploads/profile_pictures/<name>, which reads the object from S3, so the frontend
and the stored URLs are the same in both modes. On AWS the credentials come from
the instance/pod role (boto3's default chain); nothing is configured here.
"""

from __future__ import annotations

import os
import re

from flask import Response, abort, send_from_directory

BUCKET = os.environ.get("SMARTFIN_UPLOADS_BUCKET", "").strip()
PREFIX = "profile_pictures/"
CONTENT_TYPES = {"jpg": "image/jpeg", "jpeg": "image/jpeg", "png": "image/png", "webp": "image/webp"}

# Names are generated by the upload route: user_<id>_<32 hex>.<ext>. Anything else is refused,
# so a request can never reach another key in the bucket or another file on disk.
_NAME = re.compile(r"user_\d+_[0-9a-f]{32}\.(jpg|jpeg|png|webp)")


def is_valid_name(name: str) -> bool:
    return bool(name) and _NAME.fullmatch(name) is not None


def _content_type(name: str) -> str:
    return CONTENT_TYPES[name.rsplit(".", 1)[1].lower()]


class LocalStorage:
    def __init__(self, folder: str):
        self.folder = folder

    def save(self, name: str, stream) -> None:
        os.makedirs(self.folder, exist_ok=True)
        with open(os.path.join(self.folder, name), "wb") as out:
            out.write(stream.read())

    def delete(self, name: str) -> None:
        path = os.path.join(self.folder, name)
        if os.path.exists(path):
            os.remove(path)

    def response(self, name: str):
        return send_from_directory(self.folder, name)


class S3Storage:
    def __init__(self, bucket: str, client=None):
        self.bucket = bucket
        if client is None:
            import boto3
            client = boto3.client("s3", region_name=os.environ.get("AWS_REGION") or None)
        self.client = client

    def save(self, name: str, stream) -> None:
        self.client.put_object(Bucket=self.bucket, Key=PREFIX + name, Body=stream.read(), ContentType=_content_type(name))

    def delete(self, name: str) -> None:
        self.client.delete_object(Bucket=self.bucket, Key=PREFIX + name)

    def response(self, name: str):
        try:
            obj = self.client.get_object(Bucket=self.bucket, Key=PREFIX + name)
        except Exception as e:
            # botocore raises ClientError with this code for a missing object
            if getattr(e, "response", {}).get("Error", {}).get("Code") in ("NoSuchKey", "404"):
                abort(404)
            raise
        return Response(obj["Body"].read(), mimetype=_content_type(name), headers={"Cache-Control": "private, max-age=3600"})


_storage = None


def get_storage():
    """The storage for this process (S3 when SMARTFIN_UPLOADS_BUCKET is set, else the uploads folder)."""
    global _storage
    if _storage is None:
        if BUCKET:
            _storage = S3Storage(BUCKET)
        else:
            from db_core import UPLOAD_DIR
            _storage = LocalStorage(UPLOAD_DIR)
    return _storage


def set_storage(storage) -> None:
    """Swap the storage (tests)."""
    global _storage
    _storage = storage
