"""Tests for bank-statement import (parser, categorizer, preview/confirm/undo).

Fixtures are SAMPLE statements generated by fixtures/statements/make_fixtures.py.
"""

import os
import sqlite3
import sys
from pathlib import Path

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from statement_import import service
from statement_import.categorizer import categorize, extract_merchant
from statement_import.migrations import create_tables
from statement_import.parser import (StatementParseError, StatementPasswordRequired, parse_amount,
                                     parse_date, parse_statement)

FIXTURES = Path(__file__).parent / "fixtures" / "statements"
EXPECTED_COUNT, EXPECTED_DEBIT, EXPECTED_CREDIT = 19, 30310.10, 47112.40
PDF_PASSWORD = "SAUM0101"


def _read(name):
    return (FIXTURES / name).read_bytes()


# ── Parser ───────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("name,password", [
    ("hdfc_style.csv", None),            # preamble + footer summary
    ("sbi_style.xlsx", None),            # wrapped narrations across rows
    ("axis_style.csv", None),            # single amount column + Dr/Cr
    ("icici_style.pdf", None),           # multi-page, header repeated
    ("icici_style_protected.pdf", PDF_PASSWORD),
])
def test_parses_each_bank_layout_exactly(name, password):
    txns = parse_statement(name, _read(name), password)
    assert len(txns) == EXPECTED_COUNT
    assert round(sum(t.amount for t in txns if t.direction == "debit"), 2) == EXPECTED_DEBIT
    assert round(sum(t.amount for t in txns if t.direction == "credit"), 2) == EXPECTED_CREDIT
    assert txns[0].txn_date.isoformat() == "2026-09-01"
    assert txns[-1].balance == 35052.30
    assert all(t.amount > 0 for t in txns)


def test_wrapped_narration_is_rejoined():
    txns = parse_statement("sbi_style.xlsx", _read("sbi_style.xlsx"))
    assert any(t.description.startswith("NEFT CR-HDFC0000001-ACME") and "SALARY SEP 2026" in t.description for t in txns)


@pytest.mark.parametrize("password", [None, "wrong"])
def test_protected_pdf_asks_for_password(password):
    with pytest.raises(StatementPasswordRequired):
        parse_statement("s.pdf", _read("icici_style_protected.pdf"), password)


@pytest.mark.parametrize("name,data", [
    ("notes.txt", b"hello"),
    ("empty.csv", b""),
    ("random.csv", b"a,b,c\n1,2,3\n"),
    ("broken.pdf", b"not a pdf"),
])
def test_rejects_non_statements(name, data):
    with pytest.raises(StatementParseError):
        parse_statement(name, data)


def test_cell_parsing():
    assert parse_amount("1,23,456.78") == 123456.78
    assert parse_amount("₹ 500") == 500
    assert parse_amount("(120.00)") == -120
    assert parse_amount("500.00 Dr") == 500
    assert parse_amount("-") is None
    assert parse_date("01/09/26").isoformat() == "2026-09-01"
    assert parse_date("1 Sep 2026").isoformat() == "2026-09-01"
    assert parse_date("05/03/2026").isoformat() == "2026-03-05"  # day-first, never month-first
    assert parse_date("Opening Balance") is None


# ── Categorizer ──────────────────────────────────────────────────────────────

@pytest.mark.parametrize("desc,direction,category", [
    ("UPI-SWIGGY-swiggy.order@icici-ICIC0DC0099-427112345678-Order", "debit", "food"),
    ("ACH D- BAJAJ FINANCE LTD-EMI 450123", "debit", "emi"),
    ("LIC PREMIUM PAYMENT POLICY 1234", "debit", "insurance"),   # 'premium' must not match 'emi'
    ("UPI/427100001111/RAMESH KUMAR/ramesh@oksbi/rent sep", "debit", "rent"),
    ("INTEREST CREDIT FOR CURRENT QTR", "credit", "income"),      # 'current' must not match 'rent'
    ("IMPS-427155556666-PRIYA SHARMA-SBIN0001234", "debit", "other"),
    ("NEFT-TO OWN ACCOUNT XXXX1234", "debit", "transfer"),
])
def test_categorize(desc, direction, category):
    assert categorize(desc, direction, extract_merchant(desc))[0] == category


@pytest.mark.parametrize("desc,merchant", [
    ("POS 4512XXXXXX1234 AMAZON PAY INDIA", "Amazon"),
    ("UPI-SWIGGY-swiggy.order@icici-ICIC0DC0099-427112345678-Order", "Swiggy"),
    ("ATM WDL/MUMBAI ANDHERI/4512", "Cash withdrawal"),
])
def test_extract_merchant(desc, merchant):
    assert extract_merchant(desc) == merchant


def test_user_override_wins():
    desc = "IMPS-427155556666-PRIYA SHARMA-SBIN0001234"
    m = extract_merchant(desc)
    assert categorize(desc, "debit", m, {m.lower(): "rent"}) == ("rent", "user_rule")


# ── Preview / confirm / undo on a temp DB ────────────────────────────────────

@pytest.fixture
def conn(tmp_path):
    db = tmp_path / "t.db"
    c = sqlite3.connect(db)
    c.executescript("""
        CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT);
        INSERT INTO users (id, username) VALUES (1, 'a@x.com'), (2, 'b@x.com');
        CREATE TABLE monthly_budgets (id TEXT PRIMARY KEY, user_id INTEGER, month TEXT, monthly_income REAL,
                                      planned_savings REAL, created_at TEXT, updated_at TEXT);
        INSERT INTO monthly_budgets VALUES ('b1', 1, '2026-09', 45000, 5000, '', '');
        CREATE TABLE expense_entries (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, budget_id TEXT,
                                      expense_date TEXT NOT NULL, category TEXT NOT NULL,
                                      amount REAL NOT NULL CHECK (amount > 0), note TEXT,
                                      created_at TEXT, updated_at TEXT);
    """)
    c.commit()
    c.close()
    create_tables(str(db))
    c = sqlite3.connect(db)
    c.row_factory = sqlite3.Row
    yield c
    c.close()


def test_preview_then_confirm_creates_expenses(conn):
    p = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))
    assert p["summary"]["count"] == EXPECTED_COUNT and p["summary"]["duplicate_count"] == 0

    r = service.confirm(conn, 1, p["rows"])
    debits = [x for x in p["rows"] if x["direction"] == "debit" and x["category"] not in ("transfer",)]
    assert r["imported"] == EXPECTED_COUNT
    assert r["expenses_created"] == len(debits)

    exp = conn.execute("SELECT COUNT(*), SUM(amount), MIN(source), MIN(budget_id) FROM expense_entries WHERE user_id = 1").fetchone()
    assert exp[0] == len(debits)
    assert round(exp[1], 2) == round(sum(x["amount"] for x in debits), 2)
    assert exp[2] == "import" and exp[3] == "b1"  # linked to the September budget


def test_same_transactions_in_another_format_are_skipped(conn):
    service.confirm(conn, 1, service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"])
    # Same account period re-downloaded as PDF: every row should be flagged and skipped.
    p2 = service.preview(conn, 1, "icici_style.pdf", _read("icici_style.pdf"))
    assert p2["summary"]["duplicate_count"] == EXPECTED_COUNT and p2["summary"]["new_count"] == 0
    r2 = service.confirm(conn, 1, p2["rows"])
    assert r2["imported"] == 0 and r2["skipped_duplicates"] == EXPECTED_COUNT
    assert conn.execute("SELECT COUNT(*) FROM bank_transactions").fetchone()[0] == EXPECTED_COUNT


def test_identical_rows_in_one_file_are_kept(conn):
    # Two ₹568 Zomato orders on 6 Sep with different refs must both survive.
    p = service.preview(conn, 1, "axis_style.csv", _read("axis_style.csv"))
    zomato = [x for x in p["rows"] if x["merchant"] == "Zomato"]
    assert len(zomato) == 2 and zomato[0]["txn_hash"] != zomato[1]["txn_hash"]


def test_users_are_isolated(conn):
    rows = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"]
    service.confirm(conn, 1, rows)
    p_other = service.preview(conn, 2, "hdfc_style.csv", _read("hdfc_style.csv"))
    assert p_other["summary"]["duplicate_count"] == 0  # user 1's import doesn't affect user 2


def test_correction_is_learned_for_next_import(conn):
    rows = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"]
    for x in rows:
        if x["merchant"] == "Priya Sharma":
            x["category"] = "rent"
    assert service.confirm(conn, 1, rows)["rules_learned"] == 1
    service.undo_batch(conn, 1, conn.execute("SELECT import_batch_id FROM bank_transactions LIMIT 1").fetchone()[0])

    again = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"]
    priya = next(x for x in again if x["merchant"] == "Priya Sharma")
    assert priya["category"] == "rent" and priya["category_source"] == "user_rule"


def test_excluded_rows_and_non_expense_categories(conn):
    rows = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"]
    rows[1]["include"] = False                       # rent payment excluded
    rows[2]["category"] = "transfer"                 # mark a debit as self-transfer
    r = service.confirm(conn, 1, rows)
    assert r["excluded"] == 1 and r["imported"] == EXPECTED_COUNT - 1
    assert conn.execute("SELECT expense_id FROM bank_transactions WHERE category = 'transfer'").fetchone()[0] is None


def test_confirm_revalidates_client_rows(conn):
    rows = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"]
    for bad in ({"category": "lottery"}, {"amount": -5}, {"direction": "sideways"}, {"date": "31/02/2026"}):
        tampered = [dict(rows[0], **bad)] + rows[1:]
        with pytest.raises(ValueError):
            service.confirm(conn, 1, tampered)
    assert conn.execute("SELECT COUNT(*) FROM bank_transactions").fetchone()[0] == 0


def test_undo_removes_batch_and_its_expenses(conn):
    r = service.confirm(conn, 1, service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"])
    conn.execute("INSERT INTO expense_entries (id, user_id, expense_date, category, amount) VALUES ('m1', 1, '2026-09-03', 'food', 99)")
    u = service.undo_batch(conn, 1, r["batch_id"])
    assert u["transactions_removed"] == EXPECTED_COUNT and u["expenses_removed"] == r["expenses_created"]
    remaining = conn.execute("SELECT id FROM expense_entries").fetchall()
    assert [x[0] for x in remaining] == ["m1"]  # manual expense untouched
    assert service.undo_batch(conn, 2, r["batch_id"])["transactions_removed"] == 0  # other users can't undo


# ── Phase 2: recurring detection + income ────────────────────────────────────

from datetime import date as _date, timedelta as _td

from statement_import.recurring import detect_monthly_income, detect_recurring

SIX = "hdfc_style_6months.csv"


def _rows_from(name):
    out = []
    for t in parse_statement(name, _read(name)):
        m = extract_merchant(t.description)
        out.append(dict(txn_date=t.txn_date, merchant=m, direction=t.direction, amount=t.amount,
                        category=categorize(t.description, t.direction, m)[0], description=t.description))
    return out


def test_detects_exactly_the_recurring_streams():
    rec = {r["merchant"]: r for r in detect_recurring(_rows_from(SIX))}
    assert set(rec) == {"Acme Technologies", "Ramesh Kumar", "Zerodha Coin", "Bajaj Finance",
                        "Bescom Bill", "Airtel Prepaid", "Netflix"}
    # irregular spending must not be called recurring
    assert not {"Swiggy", "Uber", "Amazon"} & set(rec)
    assert rec["Acme Technologies"]["kind"] == "income"
    assert rec["Ramesh Kumar"]["kind"] == "rent"
    assert rec["Zerodha Coin"]["kind"] == "investment"
    assert rec["Bajaj Finance"]["kind"] == "emi"
    assert rec["Bescom Bill"]["amount_type"] == "variable"
    assert rec["Netflix"]["amount_type"] == "fixed"
    assert all(r["cadence"] == "monthly" and r["active"] for r in rec.values())


def test_calendar_vs_fixed_length_cycles():
    rec = {r["merchant"]: r for r in detect_recurring(_rows_from(SIX))}
    assert rec["Netflix"]["monthly_equivalent"] == 199.0
    assert rec["Netflix"]["next_expected"] == "2026-10-15"           # same day next month
    assert rec["Airtel Prepaid"]["interval_days"] == 28
    assert rec["Airtel Prepaid"]["monthly_equivalent"] == round(299 * 30.44 / 28, 2)  # 28-day plan costs more per month


def _stream(merchant, start, n, gap, amount=100.0, direction="debit", category="other"):
    return [dict(txn_date=start + _td(days=i * gap), merchant=merchant, direction=direction,
                 amount=amount, category=category) for i in range(n)]


def test_needs_three_occurrences():
    assert detect_recurring(_stream("Gym", _date(2026, 1, 5), 2, 30)) == []
    assert len(detect_recurring(_stream("Gym", _date(2026, 1, 5), 3, 30))) == 1


def test_cancelled_subscription_is_inactive():
    txns = _stream("Hotstar", _date(2026, 1, 10), 4, 30) + _stream("Netflix", _date(2026, 1, 15), 9, 30)
    rec = {r["merchant"]: r for r in detect_recurring(txns)}
    assert rec["Netflix"]["active"] and not rec["Hotstar"]["active"]


def test_weekly_and_unstable_amounts():
    weekly = detect_recurring(_stream("Milkman", _date(2026, 3, 2), 8, 7, amount=210))
    assert weekly[0]["cadence"] == "weekly" and weekly[0]["monthly_equivalent"] == round(210 * 52 / 12, 2)
    wild = [dict(t, amount=a) for t, a in zip(_stream("Random", _date(2026, 1, 1), 5, 30), [50, 900, 120, 2000, 75])]
    assert detect_recurring(wild) == []


def test_income_attributes_early_salary_to_its_month():
    income = detect_monthly_income(_rows_from(SIX))
    assert income == {m: 45000.0 for m in ("2026-04", "2026-05", "2026-06", "2026-07", "2026-08", "2026-09")}


def test_income_from_single_month_uses_salary_keyword_not_refunds():
    # one month: no recurrence possible; salary keyword still counts, refund/interest don't
    assert detect_monthly_income(_rows_from("hdfc_style.csv")) == {"2026-09": 45000.0}


def test_import_fills_income_and_links_budgets(conn):
    rows = service.preview(conn, 2, SIX, _read(SIX))["rows"]  # user 2 has no budgets
    r = service.confirm(conn, 2, rows)
    assert r["income_set"] == {m: 45000.0 for m in ("2026-04", "2026-05", "2026-06", "2026-07", "2026-08", "2026-09")}
    budgets = conn.execute("SELECT month, monthly_income, income_source FROM monthly_budgets WHERE user_id = 2").fetchall()
    assert len(budgets) == 6 and {b["income_source"] for b in budgets} == {"import"}
    assert conn.execute("SELECT COUNT(*) FROM expense_entries WHERE user_id = 2 AND budget_id IS NULL").fetchone()[0] == 0
    # SIP is investment, never a budget expense
    sip = conn.execute("SELECT category, expense_id FROM bank_transactions WHERE user_id = 2 AND merchant = 'Zerodha Coin'").fetchall()
    assert len(sip) == 6 and all(s["category"] == "investment" and s["expense_id"] is None for s in sip)


def test_manual_income_is_never_overwritten(conn):
    conn.execute("UPDATE monthly_budgets SET monthly_income = 52000, income_source = 'manual' WHERE id = 'b1'")  # user 1, Sep
    r = service.confirm(conn, 1, service.preview(conn, 1, SIX, _read(SIX))["rows"])
    assert "2026-09" not in r["income_set"] and r["income_kept_manual"] == ["2026-09"]
    assert conn.execute("SELECT monthly_income FROM monthly_budgets WHERE id = 'b1'").fetchone()[0] == 52000


def test_undo_reverts_import_set_income(conn):
    r = service.confirm(conn, 2, service.preview(conn, 2, SIX, _read(SIX))["rows"])
    service.undo_batch(conn, 2, r["batch_id"])
    assert conn.execute("SELECT COALESCE(SUM(monthly_income), 0) FROM monthly_budgets WHERE user_id = 2").fetchone()[0] == 0


def test_recurring_summary_totals(conn):
    service.confirm(conn, 2, service.preview(conn, 2, SIX, _read(SIX))["rows"])
    s = service.recurring_summary(conn, 2)
    t = s["totals"]
    assert s["months_of_history"] == 6 and t["income_monthly"] == 45000.0 and t["investments_monthly"] == 5000.0
    fixed = {r["merchant"]: r["monthly_equivalent"] for r in s["recurring"]
             if r["direction"] == "debit" and r["kind"] != "investment"}
    assert t["fixed_outflow_monthly"] == round(sum(fixed.values()), 2)
    assert "txn_ids" not in s["recurring"][0]


# ── Real-statement fixes: mode + name layout, run-together names, nameless salary ──

MODE_NAME_CSV = b"""date,DrCr,amount,balance,mode,name,Day,Month,Year,Tday
2022-01-01,Db,10000.0,90000.00,ATM,,01,01,2022,1
2022-01-02,Db,930.0,89070.00,UPI,AMAZONPAY,02,01,2022,2
2022-01-05,Cr,52000.0,141070.00,NEFT,,05,01,2022,3
2022-01-25,Cr,7.09,141077.09,ECS,,25,01,2022,4
"""


def test_parses_layout_with_mode_and_name_instead_of_narration():
    txns = parse_statement("export.csv", MODE_NAME_CSV)
    assert [(t.txn_date.isoformat(), t.description, t.direction, t.amount, t.balance) for t in txns] == [
        ("2022-01-01", "ATM", "debit", 10000.0, 90000.0),
        ("2022-01-02", "UPI AMAZONPAY", "debit", 930.0, 89070.0),
        ("2022-01-05", "NEFT", "credit", 52000.0, 141070.0),
        ("2022-01-25", "ECS", "credit", 7.09, 141077.09),
    ]
    assert extract_merchant("UPI AMAZONPAY") == "Amazonpay"


@pytest.mark.parametrize("desc,direction,category", [
    ("UPI AMAZONPAY", "debit", "shopping"),      # names run together
    ("UPI DOMINOSP", "debit", "food"),           # ... or cut short
    ("UPI HESCOMBI", "debit", "utilities"),
    ("UPI JIOINAPP", "debit", "utilities"),
    ("SBINT", "credit", "income"),
    ("UPI CHAITANYA", "debit", "other"),         # short keywords ("chai") stay whole-word
    ("UPI JIONAGAR", "debit", "other"),
    ("POS PREMIUM STORE", "debit", "other"),
])
def test_long_keywords_match_as_word_prefix(desc, direction, category):
    assert categorize(desc, direction, extract_merchant(desc))[0] == category


def _nameless_salary_rows():
    """Salary as a bare 'NEFT' on a moving pay day, mixed with unrelated NEFT credits."""
    pay_days = [(1, 5), (2, 11), (3, 21), (4, 7), (5, 3), (6, 5), (7, 2), (8, 1)]
    rows = [dict(txn_date=_date(2022, m, d), merchant="Neft", direction="credit", amount=52000.0 + 300 * (m % 3),
                 category="income", description="NEFT") for m, d in pay_days]
    rows += [dict(txn_date=_date(2022, m, d), merchant="Neft", direction="credit", amount=a,
                  category="income", description="NEFT")
             for m, d, a in [(1, 10, 2400.0), (1, 29, 2400.0), (2, 11, 2400.0), (3, 17, 2400.0), (5, 25, 3933.0)]]
    return rows


def test_nameless_salary_is_found_by_amount_cluster():
    rows = _nameless_salary_rows()
    rec = detect_recurring(rows)
    assert len(rec) == 1
    assert rec[0]["cadence"] == "monthly" and rec[0]["kind"] == "income" and rec[0]["occurrences"] == 8
    assert 52000.0 <= rec[0]["typical_amount"] <= 52600.0
    income = detect_monthly_income(rows, rec)
    # only the salary cluster counts; the other NEFT credits in the same bucket don't
    assert sorted(income) == [f"2022-{m:02d}" for m in range(1, 9)]
    assert all(52000.0 <= v <= 52600.0 for v in income.values())

