"""
PostgreSQL support.

The translation helpers are tested everywhere. The end-to-end comparison needs a PostgreSQL server:

    docker run -d --name smartfin-pg -e POSTGRES_PASSWORD=dev -e POSTGRES_DB=smartfin -p 127.0.0.1:55432:5432 postgres:17-alpine
    set TEST_DATABASE_URL=postgresql://postgres:dev@127.0.0.1:55432/smartfin
    python -m pytest unit_test/test_postgres.py

It walks through the whole API (unit_test/api_walkthrough.py) once on SQLite and once on
PostgreSQL and requires the two transcripts to be identical. WARNING: it empties the
`public` schema of the database TEST_DATABASE_URL points at. Never point it at real data.
"""

import os
import sqlite3
import subprocess
import sys
from pathlib import Path

import pytest

BACKEND = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND))

import dbapi  # noqa: E402

TEST_DATABASE_URL = os.environ.get("TEST_DATABASE_URL", "")
needs_postgres = pytest.mark.skipif(not TEST_DATABASE_URL, reason="set TEST_DATABASE_URL to run the PostgreSQL tests")


# ── Translation (no server needed) ───────────────────────────────────────────

@pytest.mark.parametrize("sql,expected", [
    ("SELECT * FROM t WHERE a = ? AND b = ?", "SELECT * FROM t WHERE a = %s AND b = %s"),
    ("SELECT * FROM t WHERE name LIKE 'idx_loan%' AND a = ?", "SELECT * FROM t WHERE name LIKE 'idx_loan%%' AND a = %s"),
    ("SELECT '?' AS literal, a FROM t WHERE b = ?", "SELECT '?' AS literal, a FROM t WHERE b = %s"),
    ("INSERT INTO t VALUES (?,?,?)", "INSERT INTO t VALUES (%s,%s,%s)"),
])
def test_placeholders_are_translated(sql, expected):
    assert dbapi.translate_params(sql) == expected


def test_create_table_is_translated_for_postgres():
    ddl = dbapi.translate_ddl("""CREATE TABLE IF NOT EXISTS t (
        id INTEGER PRIMARY KEY AUTOINCREMENT, owner INTEGER PRIMARY KEY, amount REAL NOT NULL CHECK (amount > 0),
        note TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP)""")
    assert ddl.count("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY") == 2 and "AUTOINCREMENT" not in ddl
    assert "amount DOUBLE PRECISION NOT NULL" in ddl and "REAL" not in ddl          # 8-byte floats for money
    assert "to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')" in ddl and "CURRENT_TIMESTAMP" not in ddl


def test_scripts_are_split_on_semicolons_outside_strings():
    assert dbapi._split_statements("-- a comment\nCREATE TABLE a (x TEXT DEFAULT 'a;b');\n\nCREATE INDEX i ON a(x);\n") == \
        ["CREATE TABLE a (x TEXT DEFAULT 'a;b')", "CREATE INDEX i ON a(x)"]


def test_sqlite_stays_the_default(tmp_path):
    conn = dbapi.connect(str(tmp_path / "x.db"))
    assert isinstance(conn, sqlite3.Connection) and not dbapi.is_postgres(conn)
    conn.execute("CREATE TABLE t (id INTEGER PRIMARY KEY, name TEXT)")
    assert dbapi.table_exists(conn, "t") and not dbapi.table_exists(conn, "nope")
    assert dbapi.column_names(conn, "t") == ["id", "name"] and dbapi.table_names(conn) == ["t"]
    assert dbapi.add_column_if_missing(conn, "t", "extra", "TEXT") is True
    assert dbapi.add_column_if_missing(conn, "t", "extra", "TEXT") is False
    with pytest.raises(ValueError):
        dbapi.column_names(conn, "t; DROP TABLE t")
    conn.close()


# ── Against a real server ────────────────────────────────────────────────────

@pytest.fixture
def pg():
    conn = dbapi.PgConnection(TEST_DATABASE_URL)
    conn.execute("DROP SCHEMA public CASCADE")
    conn.execute("CREATE SCHEMA public")
    conn.commit()
    yield conn
    conn.close()


@needs_postgres
def test_connection_behaves_like_sqlite3(pg):
    pg.execute("""CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE, amount REAL CHECK (amount > 0),
                  flag INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP)""")
    cur = pg.cursor()
    cur.execute("INSERT INTO t (name, amount, flag) VALUES (?, ?, ?)", ("50% off? yes", 1234567.89, True))
    assert cur.lastrowid == 1
    cur.execute("INSERT INTO t (name, amount) VALUES (?, ?)", ("second", 2.5))
    assert cur.lastrowid == 2 and cur.rowcount == 1

    row = pg.execute("SELECT * FROM t WHERE name LIKE ? ORDER BY id", ("50%",)).fetchone()
    assert (row[0], row["name"], row["amount"], row["flag"]) == (1, "50% off? yes", 1234567.89, 1)
    assert row.keys() == ["id", "name", "amount", "flag", "created_at"] and dict(row)["amount"] == 1234567.89
    assert len(row["created_at"]) == 19                                    # 'YYYY-MM-DD HH:MM:SS', as on SQLite
    with pytest.raises(IndexError):
        row["missing"]

    # errors arrive as the sqlite3 classes the code already catches, and don't break the connection
    with pytest.raises(sqlite3.IntegrityError, match="UNIQUE"):
        pg.execute("INSERT INTO t (name, amount) VALUES (?, ?)", ("second", 1))
    with pytest.raises(sqlite3.IntegrityError):
        pg.execute("INSERT INTO t (name, amount) VALUES (?, ?)", ("negative", -1))
    with pytest.raises(sqlite3.OperationalError):
        pg.execute("SELECT * FROM no_such_table")
    count, average, flags = pg.execute("SELECT COUNT(*), AVG(amount), SUM(flag) FROM t").fetchone()
    assert (count, flags) == (2, 1) and isinstance(average, float)

    assert pg.execute("INSERT INTO t (name, amount) VALUES (?, ?) ON CONFLICT (name) DO NOTHING", ("second", 9)).rowcount == 0
    assert dbapi.column_names(pg, "t")[:2] == ["id", "name"] and dbapi.table_names(pg) == ["t"]
    pg.rollback()
    assert not dbapi.table_exists(pg, "t")                                  # nothing was committed


@needs_postgres
def test_nothing_is_saved_until_commit(pg):
    """A multi-step write that fails half-way must leave no trace, exactly as on SQLite."""
    pg.execute("CREATE TABLE t (id INTEGER PRIMARY KEY, name TEXT UNIQUE)")
    pg.commit()
    pg.execute("INSERT INTO t (name) VALUES (?)", ("first",))
    with pytest.raises(sqlite3.IntegrityError):
        pg.execute("INSERT INTO t (name) VALUES (?)", ("first",))
    pg.execute("INSERT INTO t (name) VALUES (?)", ("second",))                # the failed statement alone was undone
    other = dbapi.PgConnection(TEST_DATABASE_URL)
    assert other.execute("SELECT COUNT(*) FROM t").fetchone()[0] == 0         # not visible to anyone else yet
    pg.rollback()
    assert pg.execute("SELECT COUNT(*) FROM t").fetchone()[0] == 0
    pg.execute("INSERT INTO t (name) VALUES (?)", ("kept",))
    pg.commit()
    other.rollback()
    assert other.execute("SELECT name FROM t").fetchall() == [("kept",)]
    other.close()


def _walkthrough(tmp_path, name, database_url):
    env = {**os.environ, "DATABASE_URL": database_url, "SMARTFIN_DATA_DIR": str(tmp_path / name), "SMARTFIN_LOG_FILE": "",
           "JWT_SECRET_KEY": "walkthrough-secret-0123456789abcdef0123", "PYTHONUTF8": "1", "SMARTFIN_ENV": "development"}
    out = subprocess.run([sys.executable, str(BACKEND / "unit_test" / "api_walkthrough.py")], cwd=BACKEND, env=env,
                         capture_output=True, text=True, encoding="utf-8", timeout=600)
    assert out.returncode == 0, out.stderr[-1500:]
    # one line per API call: "<name> <status> <digest>"; everything else is start-up output
    return [ln for ln in out.stdout.splitlines() if len(ln) > 38 and ln[35:38].isdigit()]


@needs_postgres
def test_the_whole_api_answers_the_same_on_both_databases(pg, tmp_path):
    pg.close()
    on_sqlite = _walkthrough(tmp_path, "sqlite", "")
    on_postgres = _walkthrough(tmp_path, "postgres", TEST_DATABASE_URL)
    assert len(on_sqlite) >= 70 and not any(" 500 " in ln[:42] for ln in on_sqlite)
    assert not (tmp_path / "postgres" / "auth.db").exists()                # the PostgreSQL run must not fall back to a file
    different = [(a, b) for a, b in zip(on_sqlite, on_postgres) if a != b]
    assert len(on_sqlite) == len(on_postgres) and different == [], "\n".join(f"sqlite:   {a[:300]}\npostgres: {b[:300]}" for a, b in different[:5])
