"""Tests for bank-statement import (parser, categorizer, preview/confirm/undo).

Fixtures are SAMPLE statements generated by fixtures/statements/make_fixtures.py.
"""

import os
import sqlite3
import sys
from pathlib import Path

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from statement_import import service
from statement_import.categorizer import categorize, extract_merchant
from statement_import.migrations import create_tables
from statement_import.parser import (StatementParseError, StatementPasswordRequired, parse_amount,
                                     parse_date, parse_statement)

FIXTURES = Path(__file__).parent / "fixtures" / "statements"
EXPECTED_COUNT, EXPECTED_DEBIT, EXPECTED_CREDIT = 19, 30310.10, 47112.40
PDF_PASSWORD = "SAUM0101"


def _read(name):
    return (FIXTURES / name).read_bytes()


# ── Parser ───────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("name,password", [
    ("hdfc_style.csv", None),            # preamble + footer summary
    ("sbi_style.xlsx", None),            # wrapped narrations across rows
    ("axis_style.csv", None),            # single amount column + Dr/Cr
    ("icici_style.pdf", None),           # multi-page, header repeated
    ("icici_style_protected.pdf", PDF_PASSWORD),
])
def test_parses_each_bank_layout_exactly(name, password):
    txns = parse_statement(name, _read(name), password)
    assert len(txns) == EXPECTED_COUNT
    assert round(sum(t.amount for t in txns if t.direction == "debit"), 2) == EXPECTED_DEBIT
    assert round(sum(t.amount for t in txns if t.direction == "credit"), 2) == EXPECTED_CREDIT
    assert txns[0].txn_date.isoformat() == "2026-09-01"
    assert txns[-1].balance == 35052.30
    assert all(t.amount > 0 for t in txns)


def test_wrapped_narration_is_rejoined():
    txns = parse_statement("sbi_style.xlsx", _read("sbi_style.xlsx"))
    assert any(t.description.startswith("NEFT CR-HDFC0000001-ACME") and "SALARY SEP 2026" in t.description for t in txns)


@pytest.mark.parametrize("password", [None, "wrong"])
def test_protected_pdf_asks_for_password(password):
    with pytest.raises(StatementPasswordRequired):
        parse_statement("s.pdf", _read("icici_style_protected.pdf"), password)


@pytest.mark.parametrize("name,data", [
    ("notes.txt", b"hello"),
    ("empty.csv", b""),
    ("random.csv", b"a,b,c\n1,2,3\n"),
    ("broken.pdf", b"not a pdf"),
])
def test_rejects_non_statements(name, data):
    with pytest.raises(StatementParseError):
        parse_statement(name, data)


def test_cell_parsing():
    assert parse_amount("1,23,456.78") == 123456.78
    assert parse_amount("₹ 500") == 500
    assert parse_amount("(120.00)") == -120
    assert parse_amount("500.00 Dr") == 500
    assert parse_amount("-") is None
    assert parse_date("01/09/26").isoformat() == "2026-09-01"
    assert parse_date("1 Sep 2026").isoformat() == "2026-09-01"
    assert parse_date("05/03/2026").isoformat() == "2026-03-05"  # day-first, never month-first
    assert parse_date("Opening Balance") is None


# ── Categorizer ──────────────────────────────────────────────────────────────

@pytest.mark.parametrize("desc,direction,category", [
    ("UPI-SWIGGY-swiggy.order@icici-ICIC0DC0099-427112345678-Order", "debit", "food"),
    ("ACH D- BAJAJ FINANCE LTD-EMI 450123", "debit", "emi"),
    ("LIC PREMIUM PAYMENT POLICY 1234", "debit", "insurance"),   # 'premium' must not match 'emi'
    ("UPI/427100001111/RAMESH KUMAR/ramesh@oksbi/rent sep", "debit", "rent"),
    ("INTEREST CREDIT FOR CURRENT QTR", "credit", "income"),      # 'current' must not match 'rent'
    ("IMPS-427155556666-PRIYA SHARMA-SBIN0001234", "debit", "other"),
    ("NEFT-TO OWN ACCOUNT XXXX1234", "debit", "transfer"),
])
def test_categorize(desc, direction, category):
    assert categorize(desc, direction, extract_merchant(desc))[0] == category


@pytest.mark.parametrize("desc,merchant", [
    ("POS 4512XXXXXX1234 AMAZON PAY INDIA", "Amazon"),
    ("UPI-SWIGGY-swiggy.order@icici-ICIC0DC0099-427112345678-Order", "Swiggy"),
    ("ATM WDL/MUMBAI ANDHERI/4512", "Cash withdrawal"),
])
def test_extract_merchant(desc, merchant):
    assert extract_merchant(desc) == merchant


def test_user_override_wins():
    desc = "IMPS-427155556666-PRIYA SHARMA-SBIN0001234"
    m = extract_merchant(desc)
    assert categorize(desc, "debit", m, {m.lower(): "rent"}) == ("rent", "user_rule")


# ── Preview / confirm / undo on a temp DB ────────────────────────────────────

@pytest.fixture
def conn(tmp_path):
    db = tmp_path / "t.db"
    c = sqlite3.connect(db)
    c.executescript("""
        CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT);
        INSERT INTO users (id, username) VALUES (1, 'a@x.com'), (2, 'b@x.com');
        CREATE TABLE monthly_budgets (id TEXT PRIMARY KEY, user_id INTEGER, month TEXT, monthly_income REAL,
                                      planned_savings REAL, created_at TEXT, updated_at TEXT);
        INSERT INTO monthly_budgets VALUES ('b1', 1, '2026-09', 45000, 5000, '', '');
        CREATE TABLE expense_entries (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, budget_id TEXT,
                                      expense_date TEXT NOT NULL, category TEXT NOT NULL,
                                      amount REAL NOT NULL CHECK (amount > 0), note TEXT,
                                      created_at TEXT, updated_at TEXT);
    """)
    c.commit()
    c.close()
    create_tables(str(db))
    c = sqlite3.connect(db)
    c.row_factory = sqlite3.Row
    yield c
    c.close()


def test_preview_then_confirm_creates_expenses(conn):
    p = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))
    assert p["summary"]["count"] == EXPECTED_COUNT and p["summary"]["duplicate_count"] == 0

    r = service.confirm(conn, 1, p["rows"])
    debits = [x for x in p["rows"] if x["direction"] == "debit" and x["category"] not in ("transfer",)]
    assert r["imported"] == EXPECTED_COUNT
    assert r["expenses_created"] == len(debits)

    exp = conn.execute("SELECT COUNT(*), SUM(amount), MIN(source), MIN(budget_id) FROM expense_entries WHERE user_id = 1").fetchone()
    assert exp[0] == len(debits)
    assert round(exp[1], 2) == round(sum(x["amount"] for x in debits), 2)
    assert exp[2] == "import" and exp[3] == "b1"  # linked to the September budget


def test_same_transactions_in_another_format_are_skipped(conn):
    service.confirm(conn, 1, service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"])
    # Same account period re-downloaded as PDF: every row should be flagged and skipped.
    p2 = service.preview(conn, 1, "icici_style.pdf", _read("icici_style.pdf"))
    assert p2["summary"]["duplicate_count"] == EXPECTED_COUNT and p2["summary"]["new_count"] == 0
    r2 = service.confirm(conn, 1, p2["rows"])
    assert r2["imported"] == 0 and r2["skipped_duplicates"] == EXPECTED_COUNT
    assert conn.execute("SELECT COUNT(*) FROM bank_transactions").fetchone()[0] == EXPECTED_COUNT


def test_identical_rows_in_one_file_are_kept(conn):
    # Two ₹568 Zomato orders on 6 Sep with different refs must both survive.
    p = service.preview(conn, 1, "axis_style.csv", _read("axis_style.csv"))
    zomato = [x for x in p["rows"] if x["merchant"] == "Zomato"]
    assert len(zomato) == 2 and zomato[0]["txn_hash"] != zomato[1]["txn_hash"]


def test_users_are_isolated(conn):
    rows = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"]
    service.confirm(conn, 1, rows)
    p_other = service.preview(conn, 2, "hdfc_style.csv", _read("hdfc_style.csv"))
    assert p_other["summary"]["duplicate_count"] == 0  # user 1's import doesn't affect user 2


def test_correction_is_learned_for_next_import(conn):
    rows = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"]
    for x in rows:
        if x["merchant"] == "Priya Sharma":
            x["category"] = "rent"
    assert service.confirm(conn, 1, rows)["rules_learned"] == 1
    service.undo_batch(conn, 1, conn.execute("SELECT import_batch_id FROM bank_transactions LIMIT 1").fetchone()[0])

    again = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"]
    priya = next(x for x in again if x["merchant"] == "Priya Sharma")
    assert priya["category"] == "rent" and priya["category_source"] == "user_rule"


def test_excluded_rows_and_non_expense_categories(conn):
    rows = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"]
    rows[1]["include"] = False                       # rent payment excluded
    rows[2]["category"] = "transfer"                 # mark a debit as self-transfer
    r = service.confirm(conn, 1, rows)
    assert r["excluded"] == 1 and r["imported"] == EXPECTED_COUNT - 1
    assert conn.execute("SELECT expense_id FROM bank_transactions WHERE category = 'transfer'").fetchone()[0] is None


def test_confirm_revalidates_client_rows(conn):
    rows = service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"]
    for bad in ({"category": "lottery"}, {"amount": -5}, {"direction": "sideways"}, {"date": "31/02/2026"}):
        tampered = [dict(rows[0], **bad)] + rows[1:]
        with pytest.raises(ValueError):
            service.confirm(conn, 1, tampered)
    assert conn.execute("SELECT COUNT(*) FROM bank_transactions").fetchone()[0] == 0


def test_undo_removes_batch_and_its_expenses(conn):
    r = service.confirm(conn, 1, service.preview(conn, 1, "hdfc_style.csv", _read("hdfc_style.csv"))["rows"])
    conn.execute("INSERT INTO expense_entries (id, user_id, expense_date, category, amount) VALUES ('m1', 1, '2026-09-03', 'food', 99)")
    u = service.undo_batch(conn, 1, r["batch_id"])
    assert u["transactions_removed"] == EXPECTED_COUNT and u["expenses_removed"] == r["expenses_created"]
    remaining = conn.execute("SELECT id FROM expense_entries").fetchall()
    assert [x[0] for x in remaining] == ["m1"]  # manual expense untouched
    assert service.undo_batch(conn, 2, r["batch_id"])["transactions_removed"] == 0  # other users can't undo
